from random import randint
true_false_questions = [
    {"question": "The Earth is the third planet from the Sun.", "answer": True},
    {"question": "Sound travels faster than light.", "answer": False},
    {"question": "Water boils at 100 degrees Celsius at sea level.", "answer": True},
    {"question": "The capital of France is Berlin.", "answer": False},
    {"question": "There are 26 letters in the English alphabet.", "answer": True},
    {"question": "The Great Wall of China is visible from space with the naked eye.", "answer": False},
    {"question": "The human body has four lungs.", "answer": False},
    {"question": "Lightning never strikes the same place twice.", "answer": False},
    {"question": "Bananas grow on trees.", "answer": False},
    {"question": "Sharks are mammals.", "answer": False},
    {"question": "Venus is hotter than Mercury.", "answer": True},
    {"question": "Gold is heavier than silver.", "answer": True},
    {"question": "The Pacific Ocean is the largest ocean on Earth.", "answer": True},
    {"question": "Bats are blind.", "answer": False},
    {"question": "Humans have more than five senses.", "answer": True},
    {"question": "Penguins can fly.", "answer": False},
    {"question": "The chemical symbol for iron is Fe.", "answer": True},
    {"question": "The square root of 64 is 6.", "answer": False},
    {"question": "An octopus has three hearts.", "answer": True},
    {"question": "Albert Einstein developed the theory of relativity.", "answer": True},
    {"question": "Lightning is hotter than the surface of the sun.", "answer": True},
    {"question": "The Sahara is the largest desert in the world.", "answer": True},
    {"question": "A group of crows is called a murder.", "answer": True},
    {"question": "Polar bears live in Antarctica.", "answer": False},
    {"question": "Slugs have four noses.", "answer": True},
    {"question": "The currency of Japan is the Yen.", "answer": True},
    {"question": "Mount Everest is the tallest mountain in the world.", "answer": True},
    {"question": "Humans can breathe in space without a spacesuit.", "answer": False},
    {"question": "Diamonds are made of carbon.", "answer": True},
    {"question": "The human skeleton is made up of over 500 bones.", "answer": False},
    {"question": "The Sun is a star.", "answer": True},
    {"question": "Lightning always strikes the tallest object.", "answer": False},
    {"question": "The Mona Lisa was painted by Vincent van Gogh.", "answer": False},
    {"question": "The speed of light is faster than the speed of sound.", "answer": True},
    {"question": "There are 12 months in a year.", "answer": True},
    {"question": "An ostrich’s eye is bigger than its brain.", "answer": True},
    {"question": "The Atlantic Ocean is the smallest ocean on Earth.", "answer": False},
    {"question": "All spiders have eight legs.", "answer": True},
    {"question": "A day on Venus is longer than its year.", "answer": True},
    {"question": "The moon is a planet.", "answer": False},
    {"question": "A leap year has 366 days.", "answer": True},
    {"question": "Humans share about 60% of their DNA with bananas.", "answer": True},
    {"question": "The chemical symbol for gold is Au.", "answer": True},
    {"question": "There are 1000 years in a century.", "answer": False},
    {"question": "Mars is known as the Red Planet.", "answer": True},
    {"question": "Birds are warm-blooded animals.", "answer": True},
    {"question": "All mammals give birth to live young.", "answer": False},
    {"question": "The currency of the United Kingdom is the Euro.", "answer": False},
    {"question": "The human heart has four chambers.", "answer": True},
    {"question": "The Statue of Liberty was a gift from Germany.", "answer": False},
    {"question": "A heptagon has eight sides.", "answer": False},
    {"question": "The Great Barrier Reef is located in Australia.", "answer": True},
    {"question": "Earth is the only planet in the solar system with liquid water on its surface.", "answer": True},
    {"question": "Spiders are insects.", "answer": False},
    {"question": "Tomatoes are vegetables.", "answer": False},
    {"question": "Light travels in a straight line.", "answer": True},
    {"question": "The Pythagorean theorem applies to all triangles.", "answer": False},
    {"question": "Pluto is still officially classified as a planet.", "answer": False},
    {"question": "A koala is a bear.", "answer": False},
    {"question": "The human body has 206 bones.", "answer": True},
    {"question": "The Eiffel Tower is in London.", "answer": False},
    {"question": "Elephants are the largest land animals.", "answer": True},
    {"question": "The atomic number of hydrogen is 1.", "answer": True},
    {"question": "Bees are the only insects that make food eaten by humans.", "answer": True},
    {"question": "Mercury is the hottest planet in the solar system.", "answer": False},
    {"question": "The liver is the largest internal organ in the human body.", "answer": True},
    {"question": "Caffeine is found naturally in tea.", "answer": True},
    {"question": "All snakes are venomous.", "answer": False},
    {"question": "Hawaii is the westernmost state of the USA.", "answer": True},
    {"question": "Octopuses have beaks.", "answer": True},
    {"question": "Dogs sweat through their tongues.", "answer": False},
    {"question": "The pancreas is part of the digestive system.", "answer": True},
    {"question": "Some fungi glow in the dark.", "answer": True},
    {"question": "Owls can rotate their heads 360 degrees.", "answer": False},
    {"question": "A group of lions is called a pride.", "answer": True},
    {"question": "Mercury is the closest planet to the Sun.", "answer": True},
    {"question": "The blue whale is the largest animal ever known to have existed.", "answer": True},
    {"question": "Butterflies taste with their feet.", "answer": True},
    {"question": "The unicorn is Scotland’s national animal.", "answer": True},
    {"question": "Jupiter has more moons than Earth.", "answer": True},
    {"question": "All birds can fly.", "answer": False},
    {"question": "The pancreas regulates blood sugar.", "answer": True},
    {"question": "The human brain stops growing after age 18.", "answer": False},
    {"question": "An adult human has 32 teeth.", "answer": True},
    {"question": "Lizards are cold-blooded.", "answer": True},
    {"question": "The speed of light is about 300,000 kilometers per second.", "answer": True},
    {"question": "Rainbows are circular.", "answer": True},
    {"question": "The Amazon River is the longest river in the world.", "answer": False},
    {"question": "Camels store water in their humps.", "answer": False},
    {"question": "Humans can distinguish over a million different colors.", "answer": True},
    {"question": "There are 60 seconds in a minute.", "answer": True},
    {"question": "The moon has no gravity.", "answer": False},
    {"question": "The lungs are the largest organ in the human body.", "answer": False},
    {"question": "There are seven continents on Earth.", "answer": True},
    {"question": "Venus spins in the opposite direction of most planets.", "answer": True},
    {"question": "Cows have four stomachs.", "answer": True},
    {"question": "A light-year measures time.", "answer": False},
    {"question": "Humans have 46 chromosomes.", "answer": True},
    {"question": "Antarctica is the driest continent.", "answer": True},
    {"question": "Snakes do not have eyelids.", "answer": True},
    {"question": "Frogs drink water through their skin.", "answer": True},
    {"question": "The human eye can distinguish about 10 million colors.", "answer": True}
]


used_nums = []


def get_question():
    num = randint(0,99)
    used_nums.append(num)
    if len(used_nums) == 100:
        return None
    while num in used_nums:
        num = randint(0,99)
    print(used_nums)
    return true_false_questions[num]

# get_question()